/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6574. Copyright MediaTek Inc. (C) 2013.
 * Sun Jan  3 17:43:09 2016
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


